services:
    environment:
      APP_HOST: bubbywoodz-kavita-reader_server_1
  server:
    image: ghcr.io/kareadita/kavita:latest
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ${APP_DATA_DIR}/manga:/manga
      - ${APP_DATA_DIR}/comics:/comics
      - ${APP_DATA_DIR}/books:/books
      - ${APP_DATA_DIR}/config:/kavita/config
