services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-kavita-reader
  web:
    image: ghcr.io/kareadita/kavita:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5000:5000"
    volumes:
      - ${APP_DATA_DIR}/manga:/manga
      - ${APP_DATA_DIR}/comics:/comics
      - ${APP_DATA_DIR}/books:/books
      - ${APP_DATA_DIR}/config:/kavita/config
