version: "0.8.6.2"

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: bubbywoodz-kavita-reader
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/manga:/manga
      - ${APP_DATA_DIR}/comics:/comics
      - ${APP_DATA_DIR}/books:/books
      - ${APP_DATA_DIR}/config:/kavita/config
    environment:
      - TZ=UTC
    ports:
      - "5000:5000"
    networks:
      - umbrel_main_network
    restart: unless-stopped
    labels:
      - "umbrel.app.name=Kavita Reader"
      - "umbrel.app.id=bubbywoodz-kavita-reader"
      - "umbrel.app.icon=https://raw.githubusercontent.com/Kareadita/Kavita/main/src/Kavita.Common/wwwroot/favicon.ico"
      - "umbrel.app.url=http://umbrel.local:5000"
      - "umbrel.app.description=A fast, feature-rich reading server for manga, comics, and books"

networks:
  umbrel_main_network:
    external: true
