version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-microbuddy_app_1
      APP_PORT: 5002
      PROXY_AUTH_ADD: "false"

  app:
    image: ghcr.io/bubbywoodz/microbuddy-dashboard:latest
    container_name: bubbywoodz-microbuddy_app_1
    working_dir: /app
    command: python3 microbuddy.py
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - SUPABASE_URL=https://tgarraczeevyrjfxzkkf.supabase.co
    volumes:
      - /home/umbrel/microbuddy-dashboard/.token:/app/.token:ro
      - /home/umbrel/microbuddy-dashboard/.supabase_anon_key:/app/.supabase_anon_key:ro
      - /home/umbrel/microbuddy-dashboard/users:/app/users
    restart: on-failure
