version: "3.3"

services:
    booktracker:
        image: wars2k/booktracker:latest
        restart: unless-stopped
        volumes:
            - ./data:/app/external
        ports:
            - 2341:5000 #replace 2341 with your desired port.
