services:
  app_proxy:
    container_name: ${APP_ID}_app_proxy
    image: getumbrel/app-proxy:1.0.0
    restart: on-failure
    environment:
      APP_HOST: app
      APP_PORT: 8000
    depends_on:
      - app
    networks:
      - default

  app:
    container_name: ${APP_ID}_app
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE:-Etc/UTC}
    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import
    ports:
      - ${APP_DYNMAP_PORT}:8123  # Dynamic for Dynmap
      - ${APP_BEDROCK_PORT}:19132/udp  # Dynamic for Bedrock
      - 30000-30100:30000-30100  # Range for Minecraft servers (monitor conflicts)
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true