services:
  crafty:
    container_name: crafty_container
    image: arcadiatechnology/crafty-4:latest
    restart: unless-stopped
    ports:
      - "8443:8443" # HTTPS
      - "8123:8123" # Dynmap
      - "19132:19132/udp" # Bedrock
      - "25565:25565" # Default Java Minecraft port
    volumes:
      - ${UMBREL_APP_DATA_DIR}/backups:/crafty/backups
      - ${UMBREL_APP_DATA_DIR}/logs:/crafty/logs
      - ${UMBREL_APP_DATA_DIR}/servers:/crafty/servers
      - ${UMBREL_APP_DATA_DIR}/config:/crafty/app/config
      - ${UMBREL_APP_DATA_DIR}/import:/crafty/import
    healthcheck:
      test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8443"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s
    labels:
      - "umbrel.app.name=Crafty Controller"
      - "umbrel.app.icon=https://docs.craftycontrol.com/img/favicon.ico"
    networks:
      - default
networks:
  default:
    external:
      name: umbrel_main_network