services:
  app:
    image: ghcr.io/bubbywoodz/stack:main
    container_name: bubbywoodz-stack_app_1
    restart: unless-stopped
    ports:
      - "8097:8097"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - TZ=America/Los_Angeles
      - PORT=8097
