version: "3.7"

services:
  app:
    image: node:16-alpine
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "$APP_SPOTIFY_BACKEND_PORT:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_SPOTIFY_BACKEND_DIR}/app:/app
    working_dir: /app
    environment:
      - SPOTIFY_CLIENT_ID=${APP_SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${APP_SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=http://${APP_DOMAIN}:${APP_SPOTIFY_BACKEND_PORT}/callback
      - SESSION_SECRET=${APP_SESSION_SECRET}
      - FRONTEND_URL=${APP_FRONTEND_URL}
      - NODE_ENV=production
    command: sh -c "npm install && node server.js"
