services:
  octobot:
    image: drakkarsoftware/octobot:stable
    volumes:
       - ${UMBREL_ROOT}/data/octobot/logs:/octobot/logs
       - ${UMBREL_ROOT}/data/octobot/backtesting:/octobot/backtesting
       - ${UMBREL_ROOT}/data/octobot/tentacles:/octobot/tentacles
       - ${UMBREL_ROOT}/data/octobot/user:/octobot/users
    ports:
       - ${PORT:-5001}:${PORT:-5001}
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock