version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  podfetch:
    container_name: podfetch
    image: ghcr.io/samtv12345/podfetch:latest
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 5m
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "${APP_PODFETCH_PORT}:8000"
    volumes:
      - ${APP_DATA_DIR}/podcasts:/app/podcasts
      - ${APP_DATA_DIR}/db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://${DEVICE_DOMAIN_NAME}:${APP_PODFETCH_PORT}
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - APP_HIDDEN_SERVICE=${APP_HIDDEN_SERVICE}
      - APP_PASSWORD=${APP_PASSWORD}
    networks:
      default:
        ipv4_address: ${APP_PODFETCH_IP}

networks:
  default:
    external:
      name: umbrel_main_network
