version: "3.9"
services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-reverb_server_1
      APP_PORT: 1971
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/bubbywoodz/swingmusic:latest@sha256:5b2a6d02ab8837e6ffa479050b16f189db84f8fe5a4cd3024e44d3d5af09824a
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - SWINGMUSIC_PORT=1971
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/music:/music:rw
