version: "3.9"
services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-reverb_server_1
      APP_PORT: 1971
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/bubbywoodz/swingmusic:latest@sha256:3fef70938685eb85baba3806c172824e4af4e0e8d31e2ecd926a6756e49ed5f6
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - SWINGMUSIC_PORT=1971
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/music:/music:rw
