version: "3.7"

services:
  spotify-proxy:
    image: bu88yw00dz/spotify-proxy:latest
    container_name: spotify-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
