version: '3.7'
services:
  server:
    image: macarooniman/auto-mcs:latest
    container_name: bubbywoodz-auto-mcs_server_1
    environment:
      - APP_PORT=8082
    ports:
      - '8082:8082'     # Web TTYD interface
      - '7001:7001'     # Telepath API
      - '25565:25565'   # Minecraft server
    volumes:
      - ${APP_DATA_DIR}/data/auto-mcs:/root/.auto-mcs
    command: >
      auto-mcs-ttyd
      -W
      -t disableLeaveAlert=true
      -t titleFixed=auto-mcs (docker)
      -t fontSize=20
      -t theme={"background": "#1A1A1A"}
      -p 8082
      -c root:auto-mcs
      tmux -u -2 new -A -s -c ./auto-mcs
    restart: unless-stopped
