services:
  auto-mcs:
    container_name: bubbywoodz-auto-mcs-server
    image: macarooniman/auto-mcs:latest
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "7001:7001"
      - "25565:25565"
    volumes:
      - ${APP_DATA_DIR}/data/auto-mcs:/root/.auto-mcs

