services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-auto-mcs-server
      APP_PORT: 8080
      PROXY_AUTH_ADD: 'false'
    container_name: bubbywoodz-auto-mcs-app-proxy

  auto-mcs:
    container_name: bubbywoodz-auto-mcs-server
    image: macarooniman/auto-mcs:latest
    restart: on-failure
    stdin_open: true
    tty: true
    command: sh -c "cd /opt/auto-mcs && python3 main.py"
    ports:
      - "7001:7001"
      - "25565:25565"
    volumes:
      - ${APP_DATA_DIR}/data/auto-mcs:/root/.auto-mcs
