version: "3"

services:
  app_proxy:
    image: getumbrel/umbrel-app-proxy:1.0.0
    environment:
      APP_HOST: app
      APP_PORT: 8082
      PROXY_AUTH_ADD: "false"

  app:
    image: macarooniman/auto-mcs:latest
    stdin_open: true
    tty: true
    restart: always
    command: >
      auto-mcs-ttyd
      -W
      -t disableLeaveAlert=true
      -t titleFixed=auto-mcs (docker)
      -t fontSize=20
      -t theme={"background": "#1A1A1A"}
      -p 8082
      -c root:auto-mcs
      tmux -u -2 new -A -s -c ./auto-mcs
    ports:
      - 7001
      - 25565
      - 8082
    volumes:
      - ${APP_DATA_DIR}/data/auto-mcs:/root/.auto-mcs
