version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: auto-mcs
      APP_PORT: 8080
      PROXY_AUTH_ADD: 'false'
    container_name: bubbywoodz-auto-mcs-app-proxy

  app:
    container_name: bubbywoodz-auto-mcs-server
    image: macarooniman/auto-mcs:latest
    stdin_open: true
    tty: true
    restart: always
    command: [
      "auto-mcs-ttyd",
      "-W",
      "-t", "disableLeaveAlert=true",
      "-t", "titleFixed=auto-mcs (docker)",
      "-t", "fontSize=20",
      "-t", "theme={\"background\": \"#1A1A1A\"}",
      "-p", "8080",
      "-c", "root:auto-mcs",
      "tmux", "-u", "-2", "new", "-A", "-s", "-c",
      "./auto-mcs"
    ]
    ports:
      - "7001:7001"  # Telepath API
      - "25565:25565"  # Minecraft server
      - "8080:8080"  # ttyd web UI
    volumes:
      - ${APP_DATA_DIR}/data/auto-mcs:/root/.auto-mcs

volumes:
  auto-mcs-data:
    name: ${APP_DATA_DIR}/data/auto-mcs