version: "3.9"
services:
  app_proxy:
    environment:
      APP_HOST: booktracker_server
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/wars2k/booktracker:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/books:/app/data
    ports:
      - "8080:8080"

  fix_permissions:
    image: ghcr.io/wars2k/booktracker:latest
    container_name: booktracker_fix_permissions
    volumes:
      - ${APP_DATA_DIR}/books:/app/data
    entrypoint: ["sh", "-c", "chmod -R 777 /app/data"]
    restart: "no"
