version: "3.3"
services:
  booktracker:
    image: wars2k/booktracker:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/external
    ports:
      - "${APP_PORT}:5000"
    environment:
      - TZ=America/Los_Angeles # Adjust to your timezone
