version: "3.7"

services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    volumes:
      - vert-data:/app/data
    restart: unless-stopped

volumes:
  vert-data:
