version: "3.9"
services:
  app_proxy:
    environment:
      APP_HOST: bubbywoodz-swingmusic_server_1
      APP_PORT: 1970
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/swingmx/swingmusic:v2.0.3
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/music:/music:rw
      - /home/umbrel/umbrel/data/storage/Music:/app/music
      - /Apps/nextcloud/data/nextcloud/data/umbrel/files/Music

  fix_permissions:
    image: ghcr.io/swingmx/swingmusic:v2.0.0.beta10
    container_name: bubbywoodz-swingmusic_fix_permissions
    volumes:
      - ${APP_DATA_DIR}/music:/music
    entrypoint: ["sh", "-c", "chmod -R 777 /music"]
    restart: "no"
